/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/about/about" |
  "/pages/apps/index" |
  "/pages/author/detail" |
  "/pages/author/form" |
  "/pages/author/list" |
  "/pages/book/detail" |
  "/pages/book/form" |
  "/pages/book/list" |
  "/pages/login/index" |
  "/pages/me/me" |
  "/pages/publisher/detail" |
  "/pages/publisher/form" |
  "/pages/publisher/list";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/apps/index" | "/pages/me/me"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
