# 监听 5173 端口
server {
    listen 5173;
    server_name localhost;
    # docs 静态文件
    location / {
        root /usr/share/nginx/html/docs;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}