"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 安全要求：生产环境必须通过 DJANGO_SECRET_KEY 环境变量注入密钥，
# 下方默认值仅供本地开发使用，禁止直接用于生产环境。
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-_ae2rmzh3uyh1rj8a37#=^o-*)9s&v%vjmxk8n1p^xflmwrj#3",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": 'dvd-admin',
#         "USER": 'root',
#         "PASSWORD": 'DVADMIN3',
#         "HOST": '127.0.0.1',
#         "PORT": 3306,
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# 语言设置
LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# 静态文件
STATIC_URL = '/static/'
# 静态文件根目录
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# 媒体文件
MEDIA_URL = '/media/'
# 媒体文件根目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 插件路由
PLUGINS_URL_PATTERNS = []

# 告诉 Django：如果收到的请求头中 X-Forwarded-Proto 是 'https'，就认为这是安全请求（HTTPS）
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# ================================================= #
# ****************** 多环境 配置  ****************** #
# ================================================= #
# 获取当前环境
ENVIRONMENT = os.getenv('ENVIRONMENT', 'dev')
# 根据不同环境，导入不同的配置文件
if ENVIRONMENT == 'prod':
    from conf.env_prod import *

    # 生产环境强制要求通过环境变量注入密钥，拒绝使用内置默认值，
    # 防止 JWT/Session/CSRF 签名密钥泄露导致账户伪造
    if not os.environ.get("DJANGO_SECRET_KEY"):
        raise RuntimeError(
            "生产环境必须设置 DJANGO_SECRET_KEY 环境变量（如：python -c 'import secrets; print(secrets.token_urlsafe(50))' 生成）"
        )
else:
    from conf.env_dev import *

# ================================================= #
# ******************* 配置缓存  ******************** #
# ================================================= #
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",  # 使用JSON序列化器，避免二进制乱码
        }
    },
}

# ================================================= #
# ****************** 一键导入插件  ****************** #
# ================================================= #


# 注册第三方插件
from extends.drf.settings import *  # drf
from extends.swagger.settings import *  # swagger API文档
from extends.jwt.settings import *  # simplejwt 认证
from extends.oa_sso.settings import *  # OA SDK 免登（原账号密码登录不变）
from extends.cors.settings import *  # cors 跨域
from extends.simple_history.settings import *  # 历史记录
from extends.import_export.settings import *  # 导入导出
from extends.celery.settings import *  # 异步
from extends.logging.settings import *  # logging 日志
from extends.websocket.settings import *  # websocket
from extends.Jinja2.settings import *  # Jinja2
from extends.email.settings import *  # email
from extends.oauth2.settings import *  # 第三方登录/注册
from extends.otp.settings import *  # 一次性密码登录/注册(手机验证码，邮箱验证码)
from extends.workflow.settings import *  # 审批

# 注册应用
from apps.system.settings import *  # 系统应用
from apps.example.settings import *  # 示例应用
