# 监听 80 端口 根据 server_name 自动路由到文档站点
server {
    listen 80;
    server_name docs.vuedj.com;
    # docs 静态文件
    location / {
        root /usr/share/nginx/html/docs;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}