# HTTP 服务：80端口，自动跳转到 HTTPS
server {
    listen 80;
    server_name docs.vuedj.com;

    # 重定向所有请求到 HTTPS 版本
    return 301 https://$server_name$request_uri;
}


# 监听 443 端口
server {
    listen 443 ssl;
    http2 on;
    server_name docs.vuedj.com;
    ssl_certificate /etc/nginx/ssl/vuedj.com.crt;   # 证书文件路径
    ssl_certificate_key /etc/nginx/ssl/vuedj.com.key;   # 私钥文件路径

    # docs 静态文件
    location / {
        root /usr/share/nginx/html/docs;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}